version: "3.9"
services:

  trojan:
    image: ${TROJAN_IMAGE}
    container_name: trojan
    restart: unless-stopped
    ports:
      - "443:443"
      - "443:443/udp"
    environment:
      - UUID=${UUID}
      - DOMAINNAME=${DOMAINNAME}
    volumes:
      - "$PWD/trojan/config/config.json:/config/config.json"
      - "$PWD/trojan/wait_for_caddy.sh:/wait_for_caddy.sh"
      - tls-data:/ssl
    links:
      - caddy:__DOCKER_CADDY__
    depends_on:
      - caddy

  caddy:
    image: ${CADDY_IMAGE}
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - DOMAINNAME=${DOMAINNAME}
    command: caddy file-server --domain ${DOMAINNAME}
    volumes:
      - "$PWD/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - $PWD/html:/var/www/html
      - tls-data:/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/${DOMAINNAME}
volumes:
  tls-data: